apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-puso-config
  namespace: development
data:
  config.yaml: |
    server:
      PORT: 3000
    database:
      URL: "postgres://qpkqricexiiquo:93e073b6a70063a95849bea222d20b0a10067d3cb18b3e27bbc58421eaaf980e@ec2-3-213-106-122.compute-1.amazonaws.com:5432/d1g0va4tfb9gtn"
    go-puso:
      VERSION: "0.0.1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-puso
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-puso-server
  template:
    metadata:
      labels:
        run: go-puso-server
    spec:
      containers:
        - name: go-puso
          image: ghcr.io/golangsrilanka/go-puso:latest
          args: ["server"]
          volumeMounts:
            - name: go-puso-config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: go-puso-config-volume
          configMap:
            name: go-puso-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-puso-entrypoint
  namespace: development
spec:
  type: NodePort
  selector:
    run: go-puso-server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30800
