info:
  contact: {}
paths:
  /healthz:
    get:
      summary: Returns health of the service
  /time:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get time diff
      tags:
      - Time
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: successfully reset
          schema:
            type: string
      summary: Create a new puso
      tags:
      - Time
swagger: "2.0"
